const mongoose = require("mongoose");
const { PAYMENT_METHODS, PAYMENT_STATUSES } = require("./constants");

const paymentRecordSchema = new mongoose.Schema(
  {
    student: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },

    batch: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Batch",
      required: true,
      index: true,
    },

    enrollmentRequest: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "EnrollmentRequest",
    },

    // Billing cycle fields used for monthly due generation.
    billingYear: {
      type: Number,
      required: true,
      min: 2000,
    },

    billingMonth: {
      type: Number,
      required: true,
      min: 1,
      max: 12,
    },

    amount: {
      type: Number,
      required: true,
      min: 0,
    },

    currency: {
      type: String,
      default: "BDT",
      uppercase: true,
      trim: true,
    },

    dueDate: {
      type: Date,
      required: true,
    },

    status: {
      type: String,
      enum: PAYMENT_STATUSES,
      default: "due",
      index: true,
    },

    // bkash | offline | manual_adjustment
    paymentMethod: {
      type: String,
      enum: PAYMENT_METHODS,
    },

    // bKash tracking metadata for sandbox/production payment confirmation.
    bkashPaymentId: {
      type: String,
      trim: true,
    },

    bkashTransactionId: {
      type: String,
      trim: true,
    },

    merchantInvoiceNumber: {
      type: String,
      trim: true,
    },

    paidAt: {
      type: Date,
    },

    // Staff actor for manual/offline updates.
    paidBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
    },

    isAutoGenerated: {
      type: Boolean,
      default: true,
    },

    note: {
      type: String,
      trim: true,
    },
  },
  {
    timestamps: true,
  }
);

// Prevent duplicate records for the same student and billing cycle.
paymentRecordSchema.index(
  { student: 1, batch: 1, billingYear: 1, billingMonth: 1 },
  { unique: true }
);

paymentRecordSchema.index({ batch: 1, billingYear: 1, billingMonth: 1, status: 1 });
paymentRecordSchema.index({ student: 1, status: 1, dueDate: 1 });

module.exports = mongoose.model("PaymentRecord", paymentRecordSchema);
